### ISSUE TITLE
Configurações Core A1 V1

### ISSUE THREAD

**Issue by zenaror** [mirandadam/klipper_gtmax3d#1]
Olá amigo, infelizmente vi esse repositório só agora, depois que configurei tudo da minha hahahah

Estou com uma Core A1 V1 da GTMax e estou com uma configuração "funcional" no momento para ela.
Gostaria que eu fizesse um PR com a config dela?

De upgrades irei fazer apenas o de sensor de filamento (que estou precisando de um fio mais longo para poder conectar na Ramps)

De resto estou com todos componentes originais, menos o Arduino que comprei um novo especifico para o Klipper, deixando assim o original intacto 

Me interessei também pelas macros e tentarei adaptar para a Core A1 V1, se me permite

**Comment by mirandadam** [comment]
Olá, @zenaro147! Fico feliz que você achou esse exemplo! Espero que tenha sido útil. Pode fazer um PR sim, lembrando que isso implica aderir à licença GPL v3 neste repositório. Gostaria de dar uma olhada no que você fez, pode me ajudar a melhorar a minha configuração.
A propósito, super recomendo o upgrade dos drivers e do ventilador frontal. Faz uma diferença muito grande no ruído.

**Comment by zenaror** [comment]
> Olá, @zenaro147! Fico feliz que você achou esse exemplo! Espero que tenha sido útil. Pode fazer um PR sim, lembrando que isso implica aderir à licença GPL v3 neste repositório. Gostaria de dar uma olhada no que você fez, pode me ajudar a melhorar a minha configuração. A propósito, super recomendo o upgrade dos drivers e do ventilador frontal. Faz uma diferença muito grande no ruído.

Obrigado, irei fazer esses upgrades com certeza assim que sobrar um dinheiro.
Você chegou a mexer algo nos drivers ou na Ramps? Ou apenas instalou eles da forma que vieram?
Vi que ele tem como conectar nas portas UART da Ramps, mas não achei muitas informações do 2209 com Ramps, apenas do 2208 (fiquei muito tempo sem acompanhar coisas de 3d, estou um pouco desatualizado de como funciona agora as coisas)

**Comment by dclobato** [comment]
@zenaro147 eu tenho uma A1v2.  Você sabe se os pinos são os mesmos? Daria para usar o do A1v1 na A1v2?
