### ISSUE TITLE
Os pinos da A1V1 são os mesmos da A1V2?

### ISSUE THREAD

**Issue by mirandadam** [mirandadam/klipper_gtmax3d#5]
@zenaro147 eu tenho uma A1v2.  Você sabe se os pinos são os mesmos? Daria para usar o do A1v1 na A1v2?

_Originally posted by @dclobato in https://github.com/mirandadam/klipper_gtmax3d/issues/1#issuecomment-1468687807_

**Comment by mirandadam** [comment]
Olá @dclobato. Não sei se os pinos são os mesmos. Você poderia perguntar ao fabricante e postar sua resposta neste thread?

**Comment by eich88** [comment]
Tenho uma Core H4 e vi que as dimensões da mesa sao as mesmas da A1V1 a única coisa que muda e o Z, o printer.cfg que foi disponibilizado é com a ramps 1.4? chegaram a fazer alguma alteracao para usar um bltouch?

**Comment by mirandadam** [comment]
* O printer.cfg é para a RAMPS 1.4 sim, que é a placa original da impressora.
* Não sei se o bltouch é diferente da sonda da A2V2, que é a minha impressora, mas me parece que é diferente.
O cabeçote da A2V2 precisa ser levado ao fim de curso no eixo X para que um "botão" seja apertado e a sonda desça. Aí você pode rodar o BED_MESH_CALIBRATE do Klipper (vide a função G29 no config.cfg) e o klipper vai fazer o levantamento da topologia da mesa, aí você tem que fazer o cabeçote apertar a sonda um pouco mais do que o ponto de ativação e então ela vai subir. Você pode testar comprimindo o botão manualmente para a sonda descer e apertando a ponta da sonda também manualmente para que ela seja recolhida para sentir os limites.
* Uma coisa que você não perguntou é se esse arquivo de configuração vai servir na sua impressora sem alterações. Eu fiz pessoalmente o da A2V2. O da A1V1 foi feito pelo @zenaro147 e eu não consigo testar porque não tenho a impressora. Outra coisa para manter em mente é que, dependendo de como você modificou a sua impressora, pode ser necessário trocar a direção de movimento dos servos.

**Comment by gugandrade** [comment]
@eich88 você chegou a fazer a configuração do Klipper na Core H4? eu tenho uma e tô querendo me arriscar.

**Comment by eich88** [comment]
comprei todas as peças para fazer nao iniciei ainda estou fazendo uma estrutura tipo a vzbot atras da impressora para tirar a eletronica dela para fora. por causa de aquecimento, mas eu vou montar o klipper nela com uma mks pi e uma robin nano v3,1.

**Comment by mirandadam** [comment]
Caros, estou fechando este issue. Se quiserem iniciar uma nova discussão, fiquem à vontade para mandar perguntas em um novo issue.

**Comment by mirandadam** [comment]
Caros, estou fechando este issue. Se quiserem iniciar uma nova discussão, fiquem à vontade para mandar perguntas em um novo issue.
