### ISSUE TITLE
Instalação na GTMax A1V1

### ISSUE THREAD

**Issue by cabped** [mirandadam/klipper_gtmax3d#7]
Boa tarde, e parabéns pelo projeto. Depois de quase 8 anos com a A1V1 resolvi fazer a troca do firmware para o Klipper. Gostaria de saber como é feita a ligação do sensor de fim de filamento, já que essa funcionalidade está no arquivo de configuração da A1V1. Como o endstop do eixo Z+ é utilizado pela eletrônica da impressora para o sensor (probe) de alinhamento não era possível utilizar o sensor de fim de filamento no Marlin de acordo com o suporte técnico... Imagino que ele entre no endstop do Z- (já que é o único disponível) mas gostaria de confirmar. Desde já muito obrigado!

**Comment by mirandadam** [comment]
Olá @cabped . O pino do sensor é definido na sessão filament_switch_sensor (vide https://www.klipper3d.org/Config_Reference.html#filament_switch_sensor). Na A2V2 é o pino PK1, mas com sinal invertido.
Veja o arquivo de configuração: https://github.com/mirandadam/klipper_gtmax3d/blob/5670dd06a4a2d056e89bb728b12b21cca856f705/printer-gtmax3d-core-a2v2.cfg#L173

Resumindo... não tem nada a ver com o endstop do Z.

Espero que dê tudo certo com a sua configuração! O arquivo da A2V2 já deve resolver o seu problema. Por favor avise neste issue se você tiver algum problema ou mesmo se der tudo certo.

**Comment by cabped** [comment]
Olá @mirandadam ,
Então. Eu já tinha visto no arquivo que o pino era o PK1 invertido, mas a questão é, qual é o pino PK1 na Ramps1.4? Revirei o diagrama da placa e não encontrei a denominação que o Klipper usa nos desenhos disponíveis na internet…

minha dúvida é como fazer a ligação física na placa do sensor de filamento, entendeu?

PS: consegui ontem fazer a instalação do Klipper com sucesso. Parabéns pelo material muito bem explicativo. Ainda não fiz todos os testes necessários antes de testar a impressão, mas devo fazer em breve. Aparentemente tudo está funcionando, desde movimento a extrusão.

Aproveitando o contato, o upgrade dos drivers que você sugeriu, TMC-2209, qual versão você utilizou? V3?

alguma dica de como instalar o drive novo na posição certa?? Kkkk

desde já muito obrigado novamente 

![IMG_6666](https://github.com/mirandadam/klipper_gtmax3d/assets/48340594/0e4cd707-880e-448b-896f-e5d1d6d7e762)

**Comment by cabped** [comment]
Boa tarde @mirandadam. Sobre o pino, já descobri, o sensor é instalado no D63 que corresponde ao PK1.

Essa relação está em: https://github.com/Klipper3d/klipper/blob/master/config/sample-aliases.cfg

Se puder me responder sobre o driver TMC2209… Parece que a versão 3 não é compatível. Usou a v1?

**Comment by cabped** [comment]
@mirandadam, qual Vref você utilizou nos drivers tmc-2209 instalados em sua A2V2?

**Comment by mirandadam** [comment]
Olá @cabped. Na caixa dos meus drivers diz BigTreeTech SKU UUU001790, no dispositivo diz TMC2209-V1.2.
Não mexi em vref, utilizei a mesma configuração que estava funcionando nos drivers originais da GTMax. Além da troca de direção, não houve mais nenhuma alteração.

**Comment by mirandadam** [comment]
Caros, estou fechando este issue. Se quiserem iniciar uma nova discussão, fiquem à vontade para mandar perguntas em um novo issue.
